/**
 * HTML formatter — a self-contained viewable report for CI artifacts.
 *
 * Output is one `<html>` document with inline CSS (no external
 * assets — the artifact has to survive being downloaded from an
 * artifact store in isolation). Keeps the markup simple enough that
 * GitHub's action-summary renderer (`GITHUB_STEP_SUMMARY`) renders
 * most of it inline when the file is small.
 *
 * Pipeline:
 *   ra11y --format html > ra11y-report.html
 *   # upload as CI artifact, or post to a static bucket
 *
 * The report is itself accessible — proper heading hierarchy, landmarks,
 * table `<caption>`, and sufficient contrast. We do eat our own dogfood.
 */

import { defineFormatter } from "../../api/plugin.ts";
import type { ReportData, ScanResult, Severity, Violation } from "../../types/violation.ts";

const INLINE_CSS = `
:root { color-scheme: light dark; }
body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.5; max-width: 80rem; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; background: #fff; }
@media (prefers-color-scheme: dark) { body { color: #eee; background: #111; } th { background: #222; } tr:nth-child(even) { background: #181818; } code { background: #222; } }
h1 { border-bottom: 2px solid currentColor; padding-bottom: 0.25rem; }
h2 { margin-top: 2rem; }
.summary { display: flex; gap: 1.5rem; flex-wrap: wrap; margin: 1rem 0; font-size: 1.1rem; }
.summary span { padding: 0.25rem 0.75rem; border-radius: 4px; border: 1px solid currentColor; }
.sev-error { color: #c00; }
.sev-warning { color: #a60; }
.sev-info { color: #06a; }
table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 0.95rem; }
th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #ddd; vertical-align: top; }
th { background: #f5f5f5; font-weight: 600; }
tr:nth-child(even) { background: #fafafa; }
code { font-family: ui-monospace, SFMono-Regular, monospace; background: #f0f0f0; padding: 0.1rem 0.35rem; border-radius: 3px; }
.file { white-space: nowrap; }
.message { max-width: 40rem; }
a { color: inherit; }
footer { margin-top: 3rem; font-size: 0.85rem; opacity: 0.7; }
`.trim();

export const htmlFormatter = defineFormatter({
  id: "html",
  format(result: ScanResult, report: ReportData): string {
    const title = `ra11y accessibility report — ${result.filesScanned} files`;
    return [
      "<!doctype html>",
      '<html lang="en">',
      "<head>",
      '<meta charset="utf-8">',
      '<meta name="viewport" content="width=device-width, initial-scale=1">',
      `<title>${escapeHtml(title)}</title>`,
      `<style>${INLINE_CSS}</style>`,
      "</head>",
      "<body>",
      "<main>",
      `<h1>${escapeHtml(title)}</h1>`,
      renderSummary(result),
      renderViolations(result.violations),
      renderCoverage(report),
      "</main>",
      '<footer>Generated by <a href="https://github.com/vanctran/ra11y">ra11y</a>.</footer>',
      "</body>",
      "</html>",
      "",
    ].join("\n");
  },
});

function renderSummary(result: ScanResult): string {
  const errors = count(result.violations, "error");
  const warnings = count(result.violations, "warning");
  const infos = count(result.violations, "info");
  const standards = result.enabledStandards.join(", ");
  return [
    '<section aria-labelledby="summary-heading">',
    '<h2 id="summary-heading">Summary</h2>',
    '<div class="summary">',
    `<span class="sev-error"><strong>${errors}</strong> errors</span>`,
    `<span class="sev-warning"><strong>${warnings}</strong> warnings</span>`,
    `<span class="sev-info"><strong>${infos}</strong> notes</span>`,
    "</div>",
    `<p>Scanned ${result.filesScanned} files in ${Math.round(result.durationMs)}ms against ${escapeHtml(standards)}.</p>`,
    "</section>",
  ].join("\n");
}

function renderViolations(violations: readonly Violation[]): string {
  if (violations.length === 0) {
    return [
      '<section aria-labelledby="findings-heading">',
      '<h2 id="findings-heading">Findings</h2>',
      "<p>No accessibility violations found.</p>",
      "</section>",
    ].join("\n");
  }
  const rows = violations.map(renderRow).join("\n");
  return [
    '<section aria-labelledby="findings-heading">',
    '<h2 id="findings-heading">Findings</h2>',
    "<table>",
    `<caption>${violations.length} violations across the scanned files.</caption>`,
    '<thead><tr><th scope="col">File</th><th scope="col">Line</th><th scope="col">Rule</th><th scope="col">Severity</th><th scope="col">Message</th></tr></thead>',
    "<tbody>",
    rows,
    "</tbody>",
    "</table>",
    "</section>",
  ].join("\n");
}

function renderRow(v: Violation): string {
  const file = escapeHtml(v.location.filePath);
  const message = escapeHtml(v.message);
  const severityClass = `sev-${v.severity}`;
  return [
    "<tr>",
    `<td class="file"><code>${file}</code></td>`,
    `<td>${v.location.line}</td>`,
    `<td><code>${escapeHtml(v.ruleId)}</code></td>`,
    `<td class="${severityClass}">${v.severity}</td>`,
    `<td class="message">${message}</td>`,
    "</tr>",
  ].join("");
}

function renderCoverage(report: ReportData): string {
  if (report.coverage.length === 0) return "";
  const rows = report.coverage
    .map(
      (e) =>
        `<tr><td><code>${escapeHtml(e.standardId)}</code></td><td>${e.automated}</td><td>${e.total}</td><td>${e.passing}</td><td>${e.failing}</td></tr>`,
    )
    .join("\n");
  return [
    '<section aria-labelledby="coverage-heading">',
    '<h2 id="coverage-heading">Coverage</h2>',
    "<table>",
    "<caption>Rule coverage of criteria per enabled standard.</caption>",
    '<thead><tr><th scope="col">Standard</th><th scope="col">Automated</th><th scope="col">Total criteria</th><th scope="col">Passing</th><th scope="col">Failing</th></tr></thead>',
    "<tbody>",
    rows,
    "</tbody>",
    "</table>",
    "</section>",
  ].join("\n");
}

function count(violations: readonly Violation[], sev: Severity): number {
  let n = 0;
  for (const v of violations) if (v.severity === sev) n += 1;
  return n;
}

function escapeHtml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
