/**
 * Rule: semantics/button-name
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; […].
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags `<button>` and `role="button"` elements with no accessible
 * name. A button's accessible name can come from:
 *   - visible text content
 *   - aria-label
 *   - aria-labelledby (pointer to another element's text)
 *   - title (last resort — not announced by every AT but counts)
 *   - for <input type="submit|button|reset">: the `value` attribute,
 *     or an implicit default string per HTML spec
 *
 * A button with only an icon child and no label is the canonical
 * failure: screen readers announce "button" with no action.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  findHtmlElementsByTag,
  findJsxElementsByTag,
  getHtmlAttribute,
  getJsxAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  htmlTextContent,
  jsxHasContentChildren,
  jsxTextContent,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

export const rule = defineRule({
  id: "semantics/button-name",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Every button must have an accessible name — via visible text, aria-label, aria-labelledby, or (for input type=submit/button) the value attribute.",
    rationale:
      "Screen readers announce a button by its accessible name. A button with only an icon child and no label is announced as 'button' — the user has no idea what it does. Icon-only buttons are one of the top-3 accessibility failures in audits.",
    goodExample: `<button aria-label="Close dialog"><svg>...</svg></button>`,
    badExample: `<button><svg>...</svg></button>`,
    normativeQuote:
      "For all user interface components the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  checkHtmlNativeButtons(doc, emit);
  checkHtmlInputButtons(doc, emit);
  checkHtmlRoleButtons(doc, emit);
}

function checkHtmlNativeButtons(doc: HtmlDocument, emit: Emit): void {
  for (const button of findHtmlElementsByTag(doc, "button")) {
    if (hasAccessibleNameHtml(button)) continue;
    emit(buildViolation("button", button.loc.start));
  }
}

function checkHtmlInputButtons(doc: HtmlDocument, emit: Emit): void {
  for (const input of findHtmlElementsByTag(doc, "input")) {
    if (!isButtonInputHtml(input)) continue;
    if (hasInputButtonNameHtml(input)) continue;
    const type = (getHtmlAttribute(input, "type") ?? "").toLowerCase();
    emit(buildViolation(`input type="${type}"`, input.loc.start));
  }
}

function checkHtmlRoleButtons(doc: HtmlDocument, emit: Emit): void {
  for (const el of walkHtmlElements(doc)) {
    const lowered = el.tagName.toLowerCase();
    if (lowered === "button" || lowered === "input") continue;
    if (getHtmlAttribute(el, "role")?.toLowerCase() !== "button") continue;
    if (hasAccessibleNameHtml(el)) continue;
    emit(buildViolation(`${el.tagName} role="button"`, el.loc.start));
  }
}

function hasAccessibleNameHtml(element: HtmlElement): boolean {
  if (htmlTextContent(element).length > 0) return true;
  if (hasHtmlAriaName(element)) return true;
  if (hasHtmlChildImgAlt(element)) return true;
  return false;
}

function hasHtmlAriaName(element: HtmlElement): boolean {
  const ariaLabel = getHtmlAttribute(element, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  if (hasHtmlAttribute(element, "aria-labelledby")) return true;
  const title = getHtmlAttribute(element, "title");
  if (title !== null && title.trim().length > 0) return true;
  return false;
}

function hasHtmlChildImgAlt(element: HtmlElement): boolean {
  for (const child of element.children) {
    if (child.kind !== "HtmlElement") continue;
    if (child.tagName.toLowerCase() !== "img") continue;
    const alt = getHtmlAttribute(child, "alt");
    if (alt !== null && alt.trim().length > 0) return true;
  }
  return false;
}

function isButtonInputHtml(element: HtmlElement): boolean {
  const type = (getHtmlAttribute(element, "type") ?? "").toLowerCase();
  return type === "button" || type === "submit" || type === "reset";
}

function hasInputButtonNameHtml(element: HtmlElement): boolean {
  const value = getHtmlAttribute(element, "value");
  if (value !== null && value.trim().length > 0) return true;
  const ariaLabel = getHtmlAttribute(element, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  if (hasHtmlAttribute(element, "aria-labelledby")) return true;
  const title = getHtmlAttribute(element, "title");
  if (title !== null && title.trim().length > 0) return true;
  // type=submit and type=reset have a UA-default label ("Submit" / "Reset").
  // The spec considers that a valid accessible name even though it's locale-
  // dependent and unhelpful.
  const type = (getHtmlAttribute(element, "type") ?? "").toLowerCase();
  if (type === "submit" || type === "reset") return true;
  return false;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  checkJsxNativeButtons(module, emit);
  checkJsxInputButtons(module, emit);
  checkJsxRoleButtons(module, emit);
}

function checkJsxNativeButtons(module: TsxModule, emit: Emit): void {
  for (const button of findJsxElementsByTag(module, "button")) {
    if (hasAccessibleNameJsx(button)) continue;
    emit(buildViolation("button", button.loc.start));
  }
}

function checkJsxInputButtons(module: TsxModule, emit: Emit): void {
  for (const input of findJsxElementsByTag(module, "input")) {
    if (!isButtonInputJsx(input)) continue;
    if (hasInputButtonNameJsx(input)) continue;
    const type = getJsxAttributeString(input, "type") ?? "";
    emit(buildViolation(`input type="${type}"`, input.loc.start));
  }
}

function checkJsxRoleButtons(module: TsxModule, emit: Emit): void {
  for (const el of walkJsxElements(module)) {
    if (el.tagName === "button" || el.tagName === "input") continue;
    if (getJsxAttributeString(el, "role") !== "button") continue;
    if (hasAccessibleNameJsx(el)) continue;
    emit(buildViolation(`${el.tagName} role="button"`, el.loc.start));
  }
}

function hasAccessibleNameJsx(element: JsxElement): boolean {
  if (jsxTextContent(element).length > 0) return true;
  // Expression children like {label} likely produce text at runtime.
  // Flagging <button>{label}</button> as "no name" is a false positive.
  if (jsxHasContentChildren(element)) return true;
  if (hasJsxAriaName(element)) return true;
  if (hasJsxChildNameSource(element)) return true;
  return false;
}

function hasJsxAriaName(element: JsxElement): boolean {
  const ariaLabel = getJsxAttributeString(element, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  if (hasJsxAttribute(element, "aria-labelledby")) return true;
  const title = getJsxAttributeString(element, "title");
  if (title !== null && title.trim().length > 0) return true;
  // aria-label as a runtime expression is a false negative we accept.
  const ariaAttr = getJsxAttribute(element, "aria-label");
  if (ariaAttr?.value?.kind === "Expression") return true;
  return false;
}

function hasJsxChildNameSource(element: JsxElement): boolean {
  for (const child of element.children) {
    if (child.kind !== "JsxElement") continue;
    // Child <img alt="..."> is an accessible name source.
    if (child.tagName === "img") {
      const alt = getJsxAttributeString(child, "alt");
      if (alt !== null && alt.trim().length > 0) return true;
    }
    // PascalCase component children (e.g., <Icon label="..."/>) likely
    // supply their own name internally. Accepting false-negatives beats
    // spamming warnings on every component-wrapped button.
    if (isPascalCase(child.tagName)) return true;
  }
  return false;
}

function isPascalCase(tag: string): boolean {
  return tag.length > 0 && tag[0] !== undefined && tag[0] >= "A" && tag[0] <= "Z";
}

function isButtonInputJsx(element: JsxElement): boolean {
  const type = getJsxAttributeString(element, "type");
  return type === "button" || type === "submit" || type === "reset";
}

function hasInputButtonNameJsx(element: JsxElement): boolean {
  const value = getJsxAttributeString(element, "value");
  if (value !== null && value.trim().length > 0) return true;
  const ariaLabel = getJsxAttributeString(element, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  if (hasJsxAttribute(element, "aria-labelledby")) return true;
  const title = getJsxAttributeString(element, "title");
  if (title !== null && title.trim().length > 0) return true;
  // Runtime-valued value={x} — can't statically verify; assume OK.
  const valueAttr = getJsxAttribute(element, "value");
  if (valueAttr?.value?.kind === "Expression") return true;
  const type = getJsxAttributeString(element, "type");
  if (type === "submit" || type === "reset") return true;
  return false;
}

function buildViolation(
  subject: string,
  loc: { line: number; column: number },
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${subject}> has no accessible name — screen readers will announce it as "button" with no action.`,
    suggestion: `Add visible text, aria-label="…", or aria-labelledby="<id>". If the button is icon-only, aria-label is the standard fix: <button aria-label="Close dialog"><svg>…</svg></button>.`,
  };
}
