/**
 * Rule: semantics/nested-interactive
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined; states,
 * > properties, and values that can be set by the user can be
 * > programmatically set; and notification of changes to these items
 * > is available to user agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags interactive elements nested inside other interactive
 * elements — e.g., a `<button>` inside an `<a href>`, or an
 * `<a href>` inside another `<a href>`. These patterns are invalid
 * per the HTML content model for `<a>` and `<button>` and produce
 * undefined assistive-technology behavior: click events bubble,
 * focus order is ambiguous, and screen readers typically announce
 * the outer element's role while the user is interacting with the
 * inner one, so the inner component's role can no longer be
 * programmatically determined in a consistent way.
 *
 * Document-scoped: builds a child→parent index and walks up the
 * chain from every interactive descendant looking for an interactive
 * ancestor. One violation per (outer, inner) pair.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type {
  HtmlDocument,
  HtmlElement,
  HtmlNode,
  JsxElement,
  JsxNode,
  TsxModule,
} from "../../types/ast.ts";

/**
 * Native HTML tags that are interactive. Some require an extra
 * attribute check (a needs href, input needs type != hidden, audio/
 * video need controls) — `isInteractiveHtml` / `isInteractiveJsx`
 * apply those.
 */
const INTERACTIVE_TAGS: ReadonlySet<string> = new Set([
  "a",
  "button",
  "input",
  "select",
  "textarea",
  "details",
  "audio",
  "video",
]);

/** ARIA roles that expose an interactive widget. */
const INTERACTIVE_ROLES: ReadonlySet<string> = new Set([
  "button",
  "link",
  "checkbox",
  "radio",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "option",
  "switch",
  "tab",
  "treeitem",
  "combobox",
  "searchbox",
  "textbox",
  "slider",
  "spinbutton",
]);

export const rule = defineRule({
  id: "semantics/nested-interactive",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "document",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "Interactive elements (links, buttons, form controls, elements with interactive ARIA roles) must not be nested inside other interactive elements.",
    rationale:
      "Nesting one interactive control inside another is invalid per the HTML content model for <a> and <button>, and the resulting DOM has no well-defined accessibility semantics. Click events bubble to the outer control, focus order is ambiguous, and screen readers typically announce the outer element's role while the user is operating the inner one — so the inner element's name and role can no longer be programmatically determined.",
    goodExample: `<a href="/settings">\n  Settings\n  <svg aria-hidden="true">...</svg>\n</a>`,
    badExample: `<a href="/card">\n  <button type="button">Action</button>\n</a>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element",
      "https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element",
    ],
  },
  afterFile(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
      return;
    }
    if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  const parentOf = buildHtmlParentMap(doc);
  for (const el of walkHtmlElements(doc)) {
    if (!isInteractiveHtml(el)) continue;
    const ancestor = findInteractiveHtmlAncestor(el, parentOf);
    if (!ancestor) continue;
    emit(
      buildHtmlViolation(
        describeHtml(ancestor),
        describeHtml(el),
        ancestor.loc.start.line,
        el.loc.start,
      ),
    );
  }
}

function findInteractiveHtmlAncestor(
  element: HtmlElement,
  parentOf: ReadonlyMap<HtmlElement, HtmlElement>,
): HtmlElement | null {
  let parent = parentOf.get(element);
  while (parent) {
    if (isInteractiveHtml(parent)) return parent;
    parent = parentOf.get(parent);
  }
  return null;
}

function isInteractiveHtml(element: HtmlElement): boolean {
  const tag = element.tagName.toLowerCase();
  if (isInteractiveHtmlTag(element, tag)) return true;
  const role = getHtmlAttribute(element, "role");
  if (role !== null && INTERACTIVE_ROLES.has(role.toLowerCase())) return true;
  return false;
}

function isInteractiveHtmlTag(element: HtmlElement, tag: string): boolean {
  if (!INTERACTIVE_TAGS.has(tag)) return false;
  if (tag === "a") return hasHtmlAttribute(element, "href");
  if (tag === "input") {
    const type = (getHtmlAttribute(element, "type") ?? "").toLowerCase();
    return type !== "hidden";
  }
  if (tag === "audio" || tag === "video") {
    return hasHtmlAttribute(element, "controls");
  }
  return true;
}

function describeHtml(element: HtmlElement): string {
  const tag = element.tagName.toLowerCase();
  const role = getHtmlAttribute(element, "role");
  if (role !== null && INTERACTIVE_ROLES.has(role.toLowerCase())) {
    // Prefer the explicit role if the element is only interactive by role.
    if (!(INTERACTIVE_TAGS.has(tag) && isInteractiveHtmlTag(element, tag))) {
      return `<${tag} role="${role.toLowerCase()}">`;
    }
  }
  if (tag === "a") return `<a href>`;
  return `<${tag}>`;
}

function buildHtmlParentMap(doc: HtmlDocument): Map<HtmlElement, HtmlElement> {
  const parentOf = new Map<HtmlElement, HtmlElement>();
  const visit = (node: HtmlNode, parent: HtmlElement | null): void => {
    if (node.kind !== "HtmlElement") return;
    if (parent) parentOf.set(node, parent);
    for (const child of node.children) visit(child, node);
  };
  for (const top of doc.children) visit(top, null);
  return parentOf;
}

// ---------------------------------------------------------------------------
// JSX
// ---------------------------------------------------------------------------

function checkJsx(module: TsxModule, emit: Emit): void {
  const parentOf = buildJsxParentMap(module);
  for (const el of walkJsxElements(module)) {
    if (isJsxPascalCase(el.tagName)) continue;
    if (!isInteractiveJsx(el)) continue;
    const ancestor = findInteractiveJsxAncestor(el, parentOf);
    if (!ancestor) continue;
    emit(
      buildHtmlViolation(
        describeJsx(ancestor),
        describeJsx(el),
        ancestor.loc.start.line,
        el.loc.start,
      ),
    );
  }
}

function findInteractiveJsxAncestor(
  element: JsxElement,
  parentOf: ReadonlyMap<JsxElement, JsxElement>,
): JsxElement | null {
  let parent = parentOf.get(element);
  while (parent) {
    // PascalCase components are opaque — don't traverse through them.
    if (isJsxPascalCase(parent.tagName)) return null;
    if (isInteractiveJsx(parent)) return parent;
    parent = parentOf.get(parent);
  }
  return null;
}

function isInteractiveJsx(element: JsxElement): boolean {
  const tag = element.tagName;
  if (isJsxPascalCase(tag)) return false;
  if (isInteractiveJsxTag(element, tag)) return true;
  const role = getJsxAttributeString(element, "role");
  if (role !== null && INTERACTIVE_ROLES.has(role)) return true;
  return false;
}

function isInteractiveJsxTag(element: JsxElement, tag: string): boolean {
  if (!INTERACTIVE_TAGS.has(tag)) return false;
  if (tag === "a") return hasJsxAttribute(element, "href");
  if (tag === "input") {
    const type = getJsxAttributeString(element, "type");
    return type !== "hidden";
  }
  if (tag === "audio" || tag === "video") {
    return hasJsxAttribute(element, "controls");
  }
  return true;
}

function describeJsx(element: JsxElement): string {
  const tag = element.tagName;
  const role = getJsxAttributeString(element, "role");
  if (role !== null && INTERACTIVE_ROLES.has(role)) {
    if (!(INTERACTIVE_TAGS.has(tag) && isInteractiveJsxTag(element, tag))) {
      return `<${tag} role="${role}">`;
    }
  }
  if (tag === "a") return `<a href>`;
  return `<${tag}>`;
}

function isJsxPascalCase(tag: string): boolean {
  const first = tag[0];
  return first !== undefined && first >= "A" && first <= "Z";
}

function buildJsxParentMap(module: TsxModule): Map<JsxElement, JsxElement> {
  const parentOf = new Map<JsxElement, JsxElement>();
  const visit = (node: JsxNode, parent: JsxElement | null): void => {
    if (node.kind !== "JsxElement") return;
    if (parent) parentOf.set(node, parent);
    for (const child of node.children) visit(child, node);
  };
  for (const top of module.jsxElements) visit(top, null);
  return parentOf;
}

// ---------------------------------------------------------------------------
// Violation builder
// ---------------------------------------------------------------------------

function buildHtmlViolation(
  outer: string,
  inner: string,
  outerLine: number,
  loc: { line: number; column: number },
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `${inner} is nested inside ${outer} (opened on line ${outerLine}) — interactive controls must not be nested. Click handling, focus order, and the accessible name/role become undefined.`,
    suggestion: `Move ${inner} out of ${outer}, or flatten the markup: keep one interactive element and make the other a plain <span>/<div>. If the outer is a card link, place the ${inner} as a sibling and use CSS to overlay it.`,
  };
}
