/**
 * Rule: aria/conflicting-role
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined […].
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags `role="X"` values that CONFLICT with the native element's
 * implicit role. Examples:
 *
 * - `<button role="link">` — button fires on Enter/Space and does not
 *   navigate; a link navigates on Enter and right-click offers
 *   "open in new tab." AT announces one thing, browser behaves like
 *   another.
 * - `<nav role="main">` — landmark mismatch; AT exposes both as
 *   separate landmark categories and a `<nav>` masquerading as `main`
 *   fractures the landmarks list.
 * - `<h1 role="button">` — breaks the rotor heading outline AT users
 *   navigate by.
 * - `<a href="…" role="button">` — anchor with href behaves like a
 *   link (right-click menu, middle-click open-in-tab) but AT announces
 *   it as a button. Flagged only when `href` is present; a
 *   handler-less `<a role="button">` is a styled-div pattern the
 *   author uses intentionally.
 *
 * Deliberately out of scope:
 *
 * - *Redundant* roles (`<a role="link">`, `<button role="button">`) —
 *   harmless and have no WCAG hook. Revisit when a best-practices
 *   standard lands.
 * - `role="none"` / `role="presentation"` on interactive elements —
 *   that is its own rule (role-presentation-on-interactive) and
 *   belongs elsewhere.
 * - `<img alt="" role="presentation">` — honored; this is the
 *   documented way to hide a decorative image from AT.
 *
 * Implicit-role resolution and the conflict matrix live in
 * `src/engine/implicit-roles.ts`.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import {
  type ImplicitRoleAttributes,
  implicitRoleFor,
  isRoleConflict,
} from "../../engine/implicit-roles.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

export const rule = defineRule({
  id: "aria/conflicting-role",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  fixClass: "verify-in-source",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "The role attribute must not contradict the native element's implicit role. Mismatched role values make assistive tech announce one thing while the browser behaves like another.",
    rationale:
      "Every native HTML element has an implicit ARIA role. Setting an incompatible explicit role (for example role='link' on a <button>, or role='main' on a <nav>) is a WCAG 4.1.2 failure: the accessible role programmatically determined no longer matches the element's actual behavior. Screen-reader users get told the control is one thing while keyboard/mouse interaction behaves like another. The fix is almost always to change the tag, not the role.",
    goodExample: `<button type="button">Save</button>
<a href="/docs">Read the docs</a>
<nav aria-label="Primary">…</nav>`,
    badExample: `<button role="link">Save</button>
<a href="/docs" role="button">Read the docs</a>
<nav role="main">…</nav>`,
    normativeQuote:
      "For all user interface components the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/html-aria/",
      "https://www.w3.org/TR/wai-aria-1.2/#role_definitions",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const element of walkHtmlElements(doc)) {
    const role = getHtmlAttribute(element, "role");
    if (!role || role.trim().length === 0) continue;
    const explicit = firstToken(role);
    if (explicit === null) continue;
    const attrs = htmlImplicitAttrs(element);
    const implicit = implicitRoleFor(element.tagName, attrs);
    if (implicit === null) continue;
    // Only fire when the anchor has an href — without it the author is
    // using <a> as a styled container and the role clarifies intent.
    if (element.tagName.toLowerCase() === "a" && attrs.href == null) continue;
    if (!isRoleConflict(implicit, explicit)) continue;
    emit(buildViolation(element.tagName, implicit, explicit, element.loc.start));
  }
}

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const element of walkJsxElements(module)) {
    const role = getJsxAttributeString(element, "role");
    if (!role || role.trim().length === 0) continue;
    const explicit = firstToken(role);
    if (explicit === null) continue;
    const attrs = jsxImplicitAttrs(element);
    const implicit = implicitRoleFor(element.tagName, attrs);
    if (implicit === null) continue;
    if (element.tagName.toLowerCase() === "a" && attrs.href == null) continue;
    if (!isRoleConflict(implicit, explicit)) continue;
    emit(buildViolation(element.tagName, implicit, explicit, element.loc.start));
  }
}

/**
 * The first non-empty token of the role attribute. ARIA allows a
 * space-separated fallback chain — we check the first token (the
 * element's primary claimed role) against the implicit role. Later
 * fallback tokens are irrelevant to the conflict check.
 */
function firstToken(roleValue: string): string | null {
  for (const raw of roleValue.split(/\s+/)) {
    const token = raw.trim();
    if (token.length > 0) return token.toLowerCase();
  }
  return null;
}

function htmlImplicitAttrs(element: HtmlElement): ImplicitRoleAttributes {
  const attrs: {
    href?: string | null;
    type?: string | null;
    scope?: string | null;
    list?: string | null;
    multiple?: string | null;
    size?: string | null;
  } = {};
  if (hasHtmlAttribute(element, "href")) attrs.href = getHtmlAttribute(element, "href");
  if (hasHtmlAttribute(element, "type")) attrs.type = getHtmlAttribute(element, "type");
  if (hasHtmlAttribute(element, "scope")) attrs.scope = getHtmlAttribute(element, "scope");
  if (hasHtmlAttribute(element, "list")) attrs.list = getHtmlAttribute(element, "list");
  if (hasHtmlAttribute(element, "multiple")) {
    attrs.multiple = getHtmlAttribute(element, "multiple") ?? "";
  }
  if (hasHtmlAttribute(element, "size")) attrs.size = getHtmlAttribute(element, "size");
  return attrs;
}

function jsxImplicitAttrs(element: JsxElement): ImplicitRoleAttributes {
  const attrs: {
    href?: string | null;
    type?: string | null;
    scope?: string | null;
    list?: string | null;
    multiple?: string | null;
    size?: string | null;
  } = {};
  // For JSX, `href={something}` (expression) still counts as
  // "the element has an href" — authors route dynamic URLs through
  // href props. Use hasJsxAttribute (which is true for both string and
  // expression values) so we don't miss the `<a href={url}>` case.
  if (hasJsxAttribute(element, "href")) {
    attrs.href = getJsxAttributeString(element, "href") ?? "";
  }
  if (hasJsxAttribute(element, "type")) {
    attrs.type = getJsxAttributeString(element, "type") ?? "";
  }
  if (hasJsxAttribute(element, "scope")) {
    attrs.scope = getJsxAttributeString(element, "scope") ?? "";
  }
  if (hasJsxAttribute(element, "list")) {
    attrs.list = getJsxAttributeString(element, "list") ?? "";
  }
  if (hasJsxAttribute(element, "multiple")) attrs.multiple = "";
  if (hasJsxAttribute(element, "size")) {
    attrs.size = getJsxAttributeString(element, "size") ?? "";
  }
  return attrs;
}

function buildViolation(
  tagName: string,
  implicit: string,
  explicit: string,
  loc: { line: number; column: number },
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${tagName}> has role="${explicit}" but its implicit role is "${implicit}" — screen readers will announce "${explicit}" while the browser behaves like a "${implicit}".`,
    suggestion: remediationSuggestion(tagName, implicit, explicit),
  };
}

function remediationSuggestion(tagName: string, implicit: string, explicit: string): string {
  const tag = tagName.toLowerCase();
  // Button↔link: the common case is "author styled a link as a button"
  // or vice versa. Both fixes are to switch the tag.
  if (implicit === "button" && explicit === "link") {
    return `If this should navigate, change <button> to <a href="…">. If it should perform an action, remove role="link" — the native <button> is already correct.`;
  }
  if (implicit === "link" && explicit === "button") {
    return `If this should perform an action (not navigate), change <a href> to <button type="button">. If it should navigate, remove role="button" — the native <a> is already correct.`;
  }
  // Landmark mismatches: swap the tag.
  const landmarks = new Set([
    "main",
    "navigation",
    "banner",
    "contentinfo",
    "complementary",
    "article",
    "region",
  ]);
  if (landmarks.has(implicit) && landmarks.has(explicit)) {
    const correctTag = tagForLandmark(explicit);
    if (correctTag) {
      return `Use <${correctTag}> for a "${explicit}" landmark. Keeping <${tag}> with role="${explicit}" makes the landmarks list inconsistent with the document outline.`;
    }
    return `Change the tag to match role="${explicit}", or remove role="${explicit}" to keep the native "${implicit}" landmark.`;
  }
  // Heading/list mismatches: the rotor + outline are the thing being broken.
  if (implicit === "heading") {
    return `Headings define the document outline screen-reader users navigate via the rotor. Remove role="${explicit}" and use a <${explicit === "button" ? "button" : "a href"}> inside the heading if the text itself needs to be interactive.`;
  }
  if (implicit === "listitem" || implicit === "list") {
    return `Lists give AT users list-navigation shortcuts. Remove role="${explicit}" and nest the interactive element inside the <${tag}>.`;
  }
  // Table mismatches.
  if (implicit === "cell" || implicit === "columnheader" || implicit === "rowheader") {
    return `Table cells give AT users row/column navigation. Remove role="${explicit}" and put the interactive element inside the <${tag}>.`;
  }
  return `Remove role="${explicit}" or change the element to a tag whose implicit role is "${explicit}".`;
}

function tagForLandmark(role: string): string | null {
  switch (role) {
    case "main":
      return "main";
    case "navigation":
      return "nav";
    case "banner":
      return "header";
    case "contentinfo":
      return "footer";
    case "complementary":
      return "aside";
    case "article":
      return "article";
    default:
      return null;
  }
}
