/**
 * Rule: aria/invalid-role
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined […].
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags `role="…"` values that are not in the WAI-ARIA 1.2 role
 * dictionary. A typo like `role="buton"` (or a non-existent abstract
 * role like `role="widget"`) collapses the element's semantics to
 * generic — screen readers announce it as a generic container instead
 * of the intended control.
 *
 * Multiple space-separated roles are allowed by ARIA as a fallback
 * chain; this rule flags the whole attribute when *every* listed role
 * is invalid, and flags the individual invalid tokens when at least
 * one is valid (the invalid tokens are dead weight but the element
 * still has a valid fallback).
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, TsxModule } from "../../types/ast.ts";

/**
 * The concrete (non-abstract) roles from WAI-ARIA 1.2. Abstract roles
 * like `widget`, `command`, `composite`, `input`, `landmark`,
 * `range`, `roletype`, `section`, `sectionhead`, `select`, `structure`,
 * `window` are intentionally excluded — they cannot be used in author
 * code and flagging them is part of this rule's job.
 *
 * Source: https://www.w3.org/TR/wai-aria-1.2/#role_definitions
 */
const VALID_ARIA_ROLES: ReadonlySet<string> = new Set([
  "alert",
  "alertdialog",
  "application",
  "article",
  "banner",
  "blockquote",
  "button",
  "caption",
  "cell",
  "checkbox",
  "code",
  "columnheader",
  "combobox",
  "complementary",
  "contentinfo",
  "definition",
  "deletion",
  "dialog",
  "directory",
  "document",
  "emphasis",
  "feed",
  "figure",
  "form",
  "generic",
  "grid",
  "gridcell",
  "group",
  "heading",
  "img",
  "insertion",
  "link",
  "list",
  "listbox",
  "listitem",
  "log",
  "main",
  "marquee",
  "math",
  "meter",
  "menu",
  "menubar",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "navigation",
  "none",
  "note",
  "option",
  "paragraph",
  "presentation",
  "progressbar",
  "radio",
  "radiogroup",
  "region",
  "row",
  "rowgroup",
  "rowheader",
  "scrollbar",
  "search",
  "searchbox",
  "separator",
  "slider",
  "spinbutton",
  "status",
  "strong",
  "subscript",
  "superscript",
  "switch",
  "tab",
  "table",
  "tablist",
  "tabpanel",
  "term",
  "textbox",
  "time",
  "timer",
  "toolbar",
  "tooltip",
  "tree",
  "treegrid",
  "treeitem",
  // DPUB-ARIA 1.1 — commonly found on EPUB/news sites.
  "doc-abstract",
  "doc-acknowledgments",
  "doc-afterword",
  "doc-appendix",
  "doc-backlink",
  "doc-biblioentry",
  "doc-bibliography",
  "doc-biblioref",
  "doc-chapter",
  "doc-colophon",
  "doc-conclusion",
  "doc-cover",
  "doc-credit",
  "doc-credits",
  "doc-dedication",
  "doc-endnote",
  "doc-endnotes",
  "doc-epigraph",
  "doc-epilogue",
  "doc-errata",
  "doc-example",
  "doc-footnote",
  "doc-foreword",
  "doc-glossary",
  "doc-glossref",
  "doc-index",
  "doc-introduction",
  "doc-noteref",
  "doc-notice",
  "doc-pagebreak",
  "doc-pagelist",
  "doc-part",
  "doc-preface",
  "doc-prologue",
  "doc-pullquote",
  "doc-qna",
  "doc-subtitle",
  "doc-tip",
  "doc-toc",
]);

export const rule = defineRule({
  id: "aria/invalid-role",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "The role attribute must be a valid WAI-ARIA role. Misspelled or non-existent roles collapse the element's semantics to generic.",
    rationale:
      "Assistive technology maps role values to its own semantic model. A misspelled role (role='buton') is treated as no role at all — the button is announced as a generic container and keyboard/action affordances are lost. Abstract roles (role='widget') are reserved for the ARIA spec itself and have no effect in author code.",
    goodExample: `<div role="button" tabindex="0">Save</div>`,
    badExample: `<div role="buton" tabindex="0">Save</div>`,
    normativeQuote:
      "For all user interface components the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/wai-aria-1.2/#role_definitions",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const element of walkHtmlElements(doc)) {
    const role = getHtmlAttribute(element, "role");
    if (role === null) continue;
    const invalid = findInvalidTokens(role);
    if (invalid.length === 0) continue;
    emit(buildViolation(element.tagName, role, invalid, element.loc.start));
  }
}

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const element of walkJsxElements(module)) {
    const role = getJsxAttributeString(element, "role");
    if (role === null) continue;
    const invalid = findInvalidTokens(role);
    if (invalid.length === 0) continue;
    emit(buildViolation(element.tagName, role, invalid, element.loc.start));
  }
}

function findInvalidTokens(roleValue: string): readonly string[] {
  const tokens = roleValue
    .split(/\s+/)
    .map((t) => t.trim())
    .filter((t) => t.length > 0);
  return tokens.filter((t) => !VALID_ARIA_ROLES.has(t.toLowerCase()));
}

function buildViolation(
  tagName: string,
  roleValue: string,
  invalid: readonly string[],
  loc: { line: number; column: number },
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  const firstBad = invalid[0] ?? roleValue;
  const nearest = nearestValidRole(firstBad);
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${tagName}> has invalid role '${firstBad}' — assistive tech will treat this element as having no role at all.`,
    suggestion: nearest
      ? `Did you mean role="${nearest}"? See https://www.w3.org/TR/wai-aria-1.2/#role_definitions for the full list of valid roles.`
      : `Remove the role attribute or replace it with a valid role from https://www.w3.org/TR/wai-aria-1.2/#role_definitions.`,
  };
}

/**
 * Returns the closest valid ARIA role by edit distance, or null if
 * nothing is within 2 edits. Keeps the suggestion friendly without
 * surfacing random noise for roles like "widget" that have no obvious
 * close match.
 */
function nearestValidRole(token: string): string | null {
  const lowered = token.toLowerCase();
  let best: string | null = null;
  let bestScore = Number.POSITIVE_INFINITY;
  for (const valid of VALID_ARIA_ROLES) {
    const score = editDistance(lowered, valid);
    if (score < bestScore) {
      bestScore = score;
      best = valid;
    }
  }
  return bestScore <= 2 ? best : null;
}

function editDistance(a: string, b: string): number {
  if (a === b) return 0;
  const rows = a.length + 1;
  const cols = b.length + 1;
  const matrix: number[] = new Array(rows * cols).fill(0);
  for (let i = 0; i < rows; i += 1) matrix[i * cols] = i;
  for (let j = 0; j < cols; j += 1) matrix[j] = j;
  for (let i = 1; i < rows; i += 1) {
    for (let j = 1; j < cols; j += 1) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      const del = (matrix[(i - 1) * cols + j] ?? 0) + 1;
      const ins = (matrix[i * cols + (j - 1)] ?? 0) + 1;
      const sub = (matrix[(i - 1) * cols + (j - 1)] ?? 0) + cost;
      matrix[i * cols + j] = Math.min(del, ins, sub);
    }
  }
  return matrix[(rows - 1) * cols + (cols - 1)] ?? Number.POSITIVE_INFINITY;
}
