/**
 * Rule: aria/required-attrs
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically
 * > set; and notification of changes to these items is available […].
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Many ARIA roles have required states/properties — `role="checkbox"`
 * without `aria-checked`, `role="combobox"` without `aria-expanded`,
 * etc. Without them the element is announced as a role with unknown
 * state, and assistive tech cannot tell the user whether the control
 * is on, off, expanded, or collapsed.
 *
 * Source: https://www.w3.org/TR/wai-aria-1.2/#requiredState
 *
 * This rule uses a static dictionary of required attributes per role.
 * It does not cover required *context* (e.g., role="menuitem" must be
 * inside a menu/menubar) — that's a separate rule.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  getHtmlAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
  walkHtmlElements,
  walkJsxElements,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

/**
 * Maps ARIA role → list of attributes the role *requires* per
 * WAI-ARIA 1.2. A role is satisfied if any one of the listed attributes
 * is present; the inner array is an "any of" group so roles that accept
 * either `aria-label` or `aria-labelledby` don't double-fire.
 *
 * Source: https://www.w3.org/TR/wai-aria-1.2/#requiredState
 */
/**
 * WAI-ARIA 1.2 required states/properties.
 *
 * Changes from ARIA 1.1 → 1.2 reflected here:
 *   - combobox: aria-expanded was required in 1.1, relaxed in 1.2
 *     (expanded state is implied by the popup's presence). Removed.
 *   - option: aria-selected is only required in single-select contexts
 *     where one option must be selected. Removed — too many false
 *     positives on standalone or multi-select options.
 *   - separator: aria-valuenow is only required when the separator is
 *     focusable. Handled via FOCUSABLE_ONLY_ROLES below.
 */
const REQUIRED_BY_ROLE: ReadonlyMap<string, readonly (readonly string[])[]> = new Map([
  ["checkbox", [["aria-checked"]]],
  ["menuitemcheckbox", [["aria-checked"]]],
  ["menuitemradio", [["aria-checked"]]],
  ["radio", [["aria-checked"]]],
  ["scrollbar", [["aria-controls"], ["aria-valuenow"]]],
  ["slider", [["aria-valuenow"]]],
  ["switch", [["aria-checked"]]],
]);

/**
 * Roles whose required attributes only apply when the element is
 * focusable (tabindex >= 0 or natively focusable).
 */
const FOCUSABLE_ONLY_ROLES: ReadonlyMap<string, readonly (readonly string[])[]> = new Map([
  ["separator", [["aria-valuenow"]]],
]);

export const rule = defineRule({
  id: "aria/required-attrs",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "ARIA roles with required states or properties must declare them. role='checkbox' needs aria-checked; role='slider' needs aria-valuenow; etc.",
    rationale:
      "When you assign a role, you promise assistive tech that the element behaves like that role. If the role requires a state attribute and you don't provide one, screen readers announce the element with unknown state — the user can't tell if the checkbox is checked or the slider's current value.",
    goodExample: `<div role="checkbox" aria-checked="false" tabindex="0">Remember me</div>`,
    badExample: `<div role="checkbox" tabindex="0">Remember me</div>`,
    normativeQuote:
      "The name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/wai-aria-1.2/#requiredState",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const element of walkHtmlElements(doc)) {
    const role = getHtmlAttribute(element, "role")?.toLowerCase();
    if (!role) continue;
    checkRoleRequirements(role, REQUIRED_BY_ROLE, element, emit);
    if (isFocusableHtml(element)) {
      checkRoleRequirements(role, FOCUSABLE_ONLY_ROLES, element, emit);
    }
  }
}

function checkRoleRequirements(
  role: string,
  map: ReadonlyMap<string, readonly (readonly string[])[]>,
  element: { tagName: string; loc: { start: { line: number; column: number } } },
  emit: Emit,
): void {
  const requirements = map.get(role);
  if (!requirements) return;
  for (const group of requirements) {
    if (group.some((attr) => hasHtmlAttribute(element as HtmlElement, attr))) continue;
    emit(buildViolation(element.tagName, role, group, element.loc.start));
  }
}

function isFocusableHtml(element: HtmlElement): boolean {
  const tabindex = getHtmlAttribute(element, "tabindex");
  if (tabindex !== null) {
    const parsed = Number.parseInt(tabindex, 10);
    if (Number.isFinite(parsed) && parsed >= 0) return true;
  }
  return false;
}

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const element of walkJsxElements(module)) {
    const role = getJsxAttributeString(element, "role")?.toLowerCase();
    if (!role) continue;
    checkRoleRequirementsJsx(role, REQUIRED_BY_ROLE, element, emit);
    if (isFocusableJsx(element)) {
      checkRoleRequirementsJsx(role, FOCUSABLE_ONLY_ROLES, element, emit);
    }
  }
}

function checkRoleRequirementsJsx(
  role: string,
  map: ReadonlyMap<string, readonly (readonly string[])[]>,
  element: JsxElement,
  emit: Emit,
): void {
  const requirements = map.get(role);
  if (!requirements) return;
  for (const group of requirements) {
    if (group.some((attr) => hasJsxAttribute(element, attr))) continue;
    emit(buildViolation(element.tagName, role, group, element.loc.start));
  }
}

function isFocusableJsx(element: JsxElement): boolean {
  const tabindex =
    getJsxAttributeString(element, "tabIndex") ?? getJsxAttributeString(element, "tabindex");
  if (tabindex !== null) {
    const parsed = Number.parseInt(tabindex, 10);
    if (Number.isFinite(parsed) && parsed >= 0) return true;
  }
  return false;
}

function buildViolation(
  tagName: string,
  role: string,
  missing: readonly string[],
  loc: { line: number; column: number },
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  const oneOf = missing.length === 1 ? missing[0] : missing.join(" or ");
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${tagName} role="${role}"> is missing required attribute ${oneOf} — assistive tech will announce the role with unknown state.`,
    suggestion: buildSuggestion(role, missing),
  };
}

function buildSuggestion(role: string, missing: readonly string[]): string {
  const first = missing[0] ?? "aria-*";
  if (first === "aria-checked") {
    return `Add ${first}="true" or "false" to indicate the current state. role="${role}" requires an explicit checked state — assistive tech won't infer it from <input checked> because this isn't a real input.`;
  }
  if (first === "aria-selected") {
    return `Add ${first}="true" or "false" to indicate which option is currently selected.`;
  }
  if (first === "aria-expanded") {
    return `Add ${first}="true" or "false" to indicate whether the combobox's popup is currently visible.`;
  }
  if (first === "aria-valuenow") {
    return `Add ${first}="<number>" to expose the slider's current value. Also consider aria-valuemin and aria-valuemax so assistive tech can announce the scale.`;
  }
  return `Add ${first} so assistive tech can announce the control's current state.`;
}
