/**
 * Rule: aria/valid-attr
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the name
 * > and role can be programmatically determined; states, properties,
 * > and values that can be set by the user can be programmatically set;
 * > and notification of changes to these items is available to user
 * > agents, including assistive technologies.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags HTML and JSX elements with `aria-*` attributes that are not in
 * the WAI-ARIA 1.2 states/properties dictionary. Typos like
 * `aria-lable` or invented attributes like `aria-foo` are silently
 * ignored by assistive tech — the screen reader announces nothing the
 * author intended. A Levenshtein-based suggestion points at the nearest
 * real attribute when the typo is within two edits.
 *
 * JSX attributes with expression values (e.g., `aria-label={runtime}`)
 * are not flagged — the attribute name is still statically checkable,
 * and an unknown attribute name is a typo whether the value is static
 * or dynamic. Expression values only matter for value-shape rules.
 */

import { defineRule } from "../../api/plugin.ts";
import { walkHtmlElements, walkJsxElements } from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

/**
 * Every aria-* state and property in WAI-ARIA 1.2.
 *
 * Source: https://www.w3.org/TR/wai-aria-1.2/#state_prop_def
 */
const VALID_ARIA_ATTRIBUTES: ReadonlySet<string> = new Set([
  "aria-activedescendant",
  "aria-atomic",
  "aria-autocomplete",
  "aria-braillelabel",
  "aria-brailleroledescription",
  "aria-busy",
  "aria-checked",
  "aria-colcount",
  "aria-colindex",
  "aria-colindextext",
  "aria-colspan",
  "aria-controls",
  "aria-current",
  "aria-describedby",
  "aria-description",
  "aria-details",
  "aria-disabled",
  "aria-dropeffect",
  "aria-errormessage",
  "aria-expanded",
  "aria-flowto",
  "aria-grabbed",
  "aria-haspopup",
  "aria-hidden",
  "aria-invalid",
  "aria-keyshortcuts",
  "aria-label",
  "aria-labelledby",
  "aria-level",
  "aria-live",
  "aria-modal",
  "aria-multiline",
  "aria-multiselectable",
  "aria-orientation",
  "aria-owns",
  "aria-placeholder",
  "aria-posinset",
  "aria-pressed",
  "aria-readonly",
  "aria-relevant",
  "aria-required",
  "aria-roledescription",
  "aria-rowcount",
  "aria-rowindex",
  "aria-rowindextext",
  "aria-rowspan",
  "aria-selected",
  "aria-setsize",
  "aria-sort",
  "aria-valuemax",
  "aria-valuemin",
  "aria-valuenow",
  "aria-valuetext",
]);

export const rule = defineRule({
  id: "aria/valid-attr",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "aria-* attributes must be defined by WAI-ARIA 1.2. Misspelled or invented aria attributes are silently ignored by assistive technology.",
    rationale:
      "Screen readers and other assistive tech only honor the aria-* states and properties defined by the WAI-ARIA spec. An attribute like aria-lable or aria-foo is not announced, not propagated to the accessibility tree, and produces no behavior whatsoever — the author's intent is lost with no runtime warning.",
    goodExample: `<div role="button" aria-pressed="false">Toggle</div>`,
    badExample: `<div role="button" aria-preessed="false">Toggle</div>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/TR/wai-aria-1.2/#state_prop_def",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Loc = { readonly line: number; readonly column: number };

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const element of walkHtmlElements(doc)) {
    checkHtmlElement(element, emit);
  }
}

function checkHtmlElement(element: HtmlElement, emit: Emit): void {
  for (const attr of element.attributes) {
    const lowered = attr.name.toLowerCase();
    if (!isAriaCandidate(lowered)) continue;
    if (VALID_ARIA_ATTRIBUTES.has(lowered)) continue;
    emit(buildViolation(element.tagName, attr.name, attr.loc.start));
  }
}

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const element of walkJsxElements(module)) {
    checkJsxElement(element, emit);
  }
}

function checkJsxElement(element: JsxElement, emit: Emit): void {
  for (const attr of element.attributes) {
    const lowered = attr.name.toLowerCase();
    if (!isAriaCandidate(lowered)) continue;
    if (VALID_ARIA_ATTRIBUTES.has(lowered)) continue;
    emit(buildViolation(element.tagName, attr.name, attr.loc.start));
  }
}

function isAriaCandidate(loweredName: string): boolean {
  return loweredName.startsWith("aria-");
}

function buildViolation(
  tagName: string,
  attrName: string,
  loc: Loc,
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  const nearest = nearestValidAttribute(attrName);
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<${tagName}> has unknown ARIA attribute '${attrName}' — assistive tech will silently ignore it and the author intent is lost.`,
    suggestion: nearest
      ? `Did you mean ${nearest}? See https://www.w3.org/TR/wai-aria-1.2/#state_prop_def for the full list of valid aria-* states and properties.`
      : `Remove '${attrName}' or replace it with a valid aria-* state or property from https://www.w3.org/TR/wai-aria-1.2/#state_prop_def.`,
  };
}

/**
 * Returns the closest valid ARIA attribute by edit distance, or null if
 * nothing is within 2 edits. Keeps the suggestion quiet for invented
 * attributes like `aria-foo` that have no obvious close match.
 */
function nearestValidAttribute(token: string): string | null {
  const lowered = token.toLowerCase();
  let best: string | null = null;
  let bestScore = Number.POSITIVE_INFINITY;
  for (const valid of VALID_ARIA_ATTRIBUTES) {
    const score = editDistance(lowered, valid);
    if (score < bestScore) {
      bestScore = score;
      best = valid;
    }
  }
  return bestScore <= 2 ? best : null;
}

function editDistance(a: string, b: string): number {
  if (a === b) return 0;
  const rows = a.length + 1;
  const cols = b.length + 1;
  const matrix: number[] = new Array(rows * cols).fill(0);
  for (let i = 0; i < rows; i += 1) matrix[i * cols] = i;
  for (let j = 0; j < cols; j += 1) matrix[j] = j;
  for (let i = 1; i < rows; i += 1) {
    for (let j = 1; j < cols; j += 1) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      const del = (matrix[(i - 1) * cols + j] ?? 0) + 1;
      const ins = (matrix[i * cols + (j - 1)] ?? 0) + 1;
      const sub = (matrix[(i - 1) * cols + (j - 1)] ?? 0) + cost;
      matrix[i * cols + j] = Math.min(del, ins, sub);
    }
  }
  return matrix[(rows - 1) * cols + (cols - 1)] ?? Number.POSITIVE_INFINITY;
}
