/**
 * Certification readiness scorecard.
 *
 * Combines automated pass rate (from coverage) and manual-review
 * completion (from a user-maintained .ra11y-manual.json file) into
 * a 0–100 readiness score per enabled standard. The formula:
 *
 *   score = 0.7 * automated_pass_rate + 0.3 * manual_completion_rate
 *
 * 70% weight on automation because that's where the tool runs daily
 * and regressions get caught. 30% on manual because compliance teams
 * still need to check the things we can't automate.
 *
 * `.ra11y-manual.json` format (generated by the user, not ra11y):
 *   {
 *     "wcag22:1.2.1": { "reviewed": true, "status": "supports", "notes": "…" },
 *     "wcag22:1.4.1": { "reviewed": true, "status": "partially-supports", "notes": "…" }
 *   }
 */

import type { Standard } from "../types/standard.ts";
import type { PerStandardCoverage } from "./coverage.ts";

export type ManualStatus = "supports" | "partially-supports" | "does-not-support" | "unknown";

export interface ManualReviewEntry {
  readonly reviewed: boolean;
  readonly status: ManualStatus;
  readonly notes?: string;
}

export type ManualReview = Readonly<Record<string, ManualReviewEntry>>;

export interface CertificationScore {
  readonly standardId: string;
  readonly standardName: string;
  readonly targetLevel: "A" | "AA" | "AAA" | "base";
  /** 0–100 overall readiness. */
  readonly readiness: number;
  readonly automated: {
    readonly total: number;
    readonly passing: number;
    readonly failing: number;
    readonly passRate: number;
  };
  readonly manual: {
    readonly total: number;
    readonly reviewed: number;
    readonly supporting: number;
    readonly completionRate: number;
  };
  readonly blockingIssues: readonly string[];
  readonly nextSteps: readonly string[];
}

const AUTOMATED_WEIGHT = 0.7;
const MANUAL_WEIGHT = 0.3;

export function buildCertificationScorecard(
  coverage: readonly PerStandardCoverage[],
  loadedStandards: readonly Standard[],
  manualReview: ManualReview = {},
  targetLevel: "A" | "AA" | "AAA" = "AA",
): readonly CertificationScore[] {
  const standardById = new Map(loadedStandards.map((s) => [s.id, s]));
  const out: CertificationScore[] = [];

  for (const entry of coverage) {
    const standard = standardById.get(entry.standardId);
    if (!standard) continue;

    const effectiveTarget = standard.levels.includes("base") ? "base" : targetLevel;
    const scoped = scopedCoverage(entry, standard, effectiveTarget);

    const passRate = scoped.automatable > 0 ? scoped.passing / scoped.automatable : 0;

    const manualStats = manualStatsFor(scoped.manualCriteria, manualReview);
    const manualCompletionRate =
      manualStats.total > 0 ? manualStats.reviewed / manualStats.total : 1;

    const readiness = Math.round(
      (AUTOMATED_WEIGHT * passRate + MANUAL_WEIGHT * manualCompletionRate) * 100,
    );

    const blockingIssues = scoped.failingCriteria.slice(0, 10);
    const nextSteps = buildNextSteps(scoped, manualStats);

    out.push({
      standardId: entry.standardId,
      standardName: entry.standardName,
      targetLevel: effectiveTarget,
      readiness,
      automated: {
        total: scoped.automatable,
        passing: scoped.passing,
        failing: scoped.failing,
        passRate: Math.round(passRate * 100),
      },
      manual: {
        total: manualStats.total,
        reviewed: manualStats.reviewed,
        supporting: manualStats.supporting,
        completionRate: Math.round(manualCompletionRate * 100),
      },
      blockingIssues,
      nextSteps,
    });
  }

  return out;
}

interface ScopedCoverage {
  readonly automatable: number;
  readonly passing: number;
  readonly failing: number;
  readonly failingCriteria: readonly string[];
  readonly manualCriteria: readonly string[];
}

function scopedCoverage(
  entry: PerStandardCoverage,
  standard: Standard,
  targetLevel: "A" | "AA" | "AAA" | "base",
): ScopedCoverage {
  // Restrict to criteria at or below the target conformance level.
  const applicableLevels: ReadonlySet<string> = new Set(levelsAtOrBelow(targetLevel));
  const scopedCriteria = standard.criteria.filter((c) => applicableLevels.has(c.level));
  const scopedIds = new Set(scopedCriteria.map((c) => c.id));

  const failingCriteria = entry.failingCriteria.filter((id) => scopedIds.has(id));
  const manualCriteria = entry.manualCriteria.filter((id) => scopedIds.has(id));

  let automatable = 0;
  let passing = 0;
  for (const c of scopedCriteria) {
    if (c.automatable === "manual") continue;
    automatable += 1;
    if (!failingCriteria.includes(c.id)) passing += 1;
  }

  return {
    automatable,
    passing,
    failing: failingCriteria.length,
    failingCriteria,
    manualCriteria,
  };
}

function levelsAtOrBelow(target: "A" | "AA" | "AAA" | "base"): readonly string[] {
  if (target === "base") return ["base"];
  if (target === "A") return ["A"];
  if (target === "AA") return ["A", "AA"];
  return ["A", "AA", "AAA"];
}

function manualStatsFor(
  criterionIds: readonly string[],
  review: ManualReview,
): { total: number; reviewed: number; supporting: number } {
  let reviewed = 0;
  let supporting = 0;
  for (const id of criterionIds) {
    const entry = review[id];
    if (entry?.reviewed) {
      reviewed += 1;
      if (entry.status === "supports") supporting += 1;
    }
  }
  return { total: criterionIds.length, reviewed, supporting };
}

function buildNextSteps(
  scoped: ScopedCoverage,
  manualStats: { total: number; reviewed: number },
): string[] {
  const steps: string[] = [];
  if (scoped.failing > 0) {
    steps.push(
      `Fix ${scoped.failing} failing automated criterion(s). Run \`ra11y --format terminal\` for locations and suggestions.`,
    );
  }
  const pending = manualStats.total - manualStats.reviewed;
  if (pending > 0) {
    steps.push(
      `Complete ${pending} pending manual review(s). Generate the worksheet with \`ra11y --checklist > checklist.md\`.`,
    );
  }
  if (steps.length === 0) {
    steps.push("Scorecard is green. Schedule periodic re-scans in CI to catch regressions.");
  }
  return steps;
}

/** Render a compact terminal/Markdown summary. */
export function renderCertificationMarkdown(scores: readonly CertificationScore[]): string {
  const lines: string[] = [];
  lines.push("# Certification Readiness Scorecard");
  lines.push("");
  for (const score of scores) {
    lines.push(`## ${score.standardName} — target Level ${score.targetLevel}`);
    lines.push("");
    lines.push(`**Readiness: ${score.readiness} / 100**`);
    lines.push("");
    lines.push(
      `- Automated: ${score.automated.passing}/${score.automated.total} passing (${score.automated.passRate}%)`,
    );
    lines.push(
      `- Manual review: ${score.manual.reviewed}/${score.manual.total} complete (${score.manual.completionRate}%)`,
    );
    lines.push("");
    if (score.blockingIssues.length > 0) {
      lines.push("### Blocking issues");
      for (const id of score.blockingIssues) lines.push(`- ${id}`);
      lines.push("");
    }
    lines.push("### Next steps");
    for (const step of score.nextSteps) lines.push(`- ${step}`);
    lines.push("");
  }
  return lines.join("\n");
}
