/**
 * Deterministic detection of compiled-CSS / bundler-output files among
 * the set of files a scan has already parsed.
 *
 * Surfaces as `meta.scannedBuildArtifacts: string[]` on `scan_project`
 * responses — a *label*, not a filter. Findings on these files still
 * appear in `files`; the meta entry tells the consuming agent "this
 * finding sits on a generated file; investigate before editing
 * source." Per CLAUDE.md §1 "Labeled buckets are suppression too," a
 * label earns its place only when it is *provable from the code*
 * rather than heuristic. The three signals below each clear that bar:
 *
 *   1. Escape-bracket Tailwind utility selectors (`\[400px\]`,
 *      `\:focus-visible:`, `\[--…]`). Hand-written CSS does not
 *      contain these — they are emitted by Tailwind's JIT compiler as
 *      the CSS-escaped form of utility class names like `w-[400px]`.
 *      One match is proof the file came from the build.
 *   2. `.css` files with >1000 physical lines. Hand-written CSS rarely
 *      approaches that size; compiled output from Tailwind, preflight,
 *      or a utility-first framework routinely does. Not a heuristic
 *      about "probably compiled" — a size threshold that is provably
 *      unusual for hand-authored stylesheets.
 *   3. Files whose paths live under a known bundler output directory
 *      (`/dist/`, `/build/`, `/.next/`, `/.svelte-kit/`, `/.output/`,
 *      `/static/assets/`). These are canonical output locations; a
 *      file there is generated by definition.
 *
 * Any single match labels the file. The intent is not to cross-check
 * signals — the label is additive information and over-labeling is
 * the cheap failure mode (agents dismiss in one read). Under-labeling
 * is the expensive one: a generated file slips through as
 * hand-written, the agent edits it, and the edit is overwritten on
 * the next build.
 */

/**
 * Matches the CSS-escaped-bracket and escaped-colon forms Tailwind
 * emits for utility classes. Examples of compiled output:
 *   .w-\[400px\]         → `\[400px\]` (or `\[400px]` on some emitters)
 *   .group\:focus-visible:before → `\:focus-visible:`
 *   .bg-\[--my-color\]   → `\[--`
 *
 * The bracket forms accept an optional `\` before the closing `]`
 * because different Tailwind/PostCSS pipelines emit either `\]` or a
 * bare `]`. A single occurrence of any alternative is sufficient;
 * these patterns do not appear in idiomatic hand-written CSS.
 */
const TAILWIND_ESCAPED_SELECTOR =
  /\\\[\d+px\\?\]|\\\[\d+rem\\?\]|\\\[\d+%\\?\]|\\:focus-visible:|\\\[--/u;

/**
 * Substring markers for canonical bundler output directories. The
 * matcher tolerates each marker either bracketed by `/` inside the
 * path OR sitting at the start of a relative path (`dist/main.css`).
 * A bare filename like `dist.ts` at the repo root stays unmatched —
 * the probe requires a trailing `/` to confirm it's a directory
 * segment, not a filename prefix.
 */
const BUILD_DIR_MARKERS = [
  "dist/",
  "build/",
  ".next/",
  ".svelte-kit/",
  ".output/",
  "static/assets/",
] as const;

/**
 * Line-count threshold above which a `.css` file counts as compiled
 * output. Hand-written stylesheets rarely cross this line; Tailwind's
 * preflight plus any nontrivial utility surface does on the first
 * build.
 */
const COMPILED_CSS_LINE_THRESHOLD = 1000;

/**
 * Pure detector: given a file path and its source text, returns true
 * when any of the three signals fires. O(file size) — one regex pass
 * plus a newline count when the file is `.css`.
 *
 * The function is intentionally permissive about file extensions: a
 * file discovered under `/dist/assets/` is a build artifact regardless
 * of whether it ends in `.css` or `.html`. The escaped-selector probe
 * is gated to `.css` (JSX sources can contain those patterns as string
 * literals, which are not compiled CSS).
 */
export function isBuildArtifact(filePath: string, source: string): boolean {
  if (matchesBuildDirMarker(filePath)) return true;
  if (!isCssPath(filePath)) return false;
  if (TAILWIND_ESCAPED_SELECTOR.test(source)) return true;
  if (countLines(source) > COMPILED_CSS_LINE_THRESHOLD) return true;
  return false;
}

function matchesBuildDirMarker(filePath: string): boolean {
  // Normalize backslashes so Windows-style paths ("C:\proj\dist\…")
  // are handled. The matcher accepts a marker either preceded by `/`
  // anywhere in the path OR sitting at the very start — that covers
  // the two canonical cases ("/proj/dist/x.css" and "dist/x.css")
  // without mislabeling a root-level file literally named "dist.ts".
  const normalized = filePath.replace(/\\/g, "/");
  for (const marker of BUILD_DIR_MARKERS) {
    if (normalized.startsWith(marker) || normalized.includes(`/${marker}`)) return true;
  }
  return false;
}

function isCssPath(filePath: string): boolean {
  // Case-insensitive .css suffix check. Avoids a regex for what is a
  // two-field string probe and keeps the hot-path allocation-free.
  const lower = filePath.toLowerCase();
  return lower.endsWith(".css");
}

function countLines(source: string): number {
  // One physical-line count per file — cheaper than String.prototype.split
  // on long files because we don't materialize the array. The scanner's
  // source text uses `\n` as line terminator (the parsers normalize);
  // counting `\n` plus 1 for the trailing line is the standard form.
  let n = 1;
  for (let i = 0; i < source.length; i += 1) {
    if (source.charCodeAt(i) === 10) n += 1;
  }
  return n;
}

/**
 * Batch helper: classify each `(filePath, source)` pair and return the
 * subset that are build artifacts. Caller-side iteration is folded in
 * so `tool-scan-project.ts` can call once. Sort order matches the
 * input order — callers wanting deterministic output sort upstream.
 */
export function collectBuildArtifacts(
  files: readonly { readonly filePath: string; readonly source: string }[],
): readonly string[] {
  const out: string[] = [];
  for (const file of files) {
    if (isBuildArtifact(file.filePath, file.source)) out.push(file.filePath);
  }
  return out;
}
