#!/usr/bin/env bun
/**
 * autoresearch harness for branch `autoresearch/apr14-manual-to-auto`.
 *
 * Scalar metric: number of distinct criterion IDs that have *some*
 * automation — either a built-in rule's `satisfies` entry or a built-in
 * candidate finder's `criterionIds` entry. Higher is better; the loop
 * tries to drag criteria out of the manual-only checklist bucket.
 *
 * Do NOT edit this file during a trial. Autoresearch discipline — the
 * harness is frozen for the run.
 *
 * Emit:
 *   metric: <N>                     — unique covered criterion IDs
 *   breakdown: rules=<R> finders=<F>
 *   newly_covered:                  — optional list (rendered if env set)
 */

import { spawnSync } from "node:child_process";

function gate(label: string, argv: readonly string[]): void {
  const [cmd, ...rest] = argv;
  if (!cmd) throw new Error(`[harness] empty gate argv for ${label}`);
  const r = spawnSync(cmd, rest, { stdio: "inherit" });
  if (r.status !== 0) {
    process.stderr.write(`[harness] gate failed: ${label}\n`);
    process.exit(1);
  }
}

if (process.env.SKIP_GATES !== "1") {
  gate("typecheck", ["bun", "run", "typecheck"]);
  gate("tests", ["bun", "test", "tests/unit/rules/", "tests/unit/review/"]);
}

const { BUILTIN_RULES } = await import("../src/rules/index.ts");
const { BUILTIN_CANDIDATE_FINDERS } = await import("../src/review/index.ts");
const { BUILTIN_STANDARDS } = await import("../src/standards/index.ts");

const covered = new Set<string>();
const ruleCovered = new Set<string>();
const finderCovered = new Set<string>();

for (const rule of BUILTIN_RULES) {
  for (const id of rule.satisfies) {
    covered.add(id);
    ruleCovered.add(id);
  }
}
for (const finder of BUILTIN_CANDIDATE_FINDERS) {
  for (const id of finder.criterionIds) {
    covered.add(id);
    finderCovered.add(id);
  }
}

const totalCriteria = BUILTIN_STANDARDS.reduce((n, s) => n + s.criteria.length, 0);

process.stdout.write(`metric: ${covered.size}\n`);
process.stdout.write(
  `breakdown: rules=${BUILTIN_RULES.length} finders=${BUILTIN_CANDIDATE_FINDERS.length} total_criteria=${totalCriteria}\n`,
);
process.stdout.write(
  `split: rule_covered=${ruleCovered.size} finder_covered=${finderCovered.size}\n`,
);

if (process.env.SHOW_COVERAGE === "1") {
  process.stdout.write("covered:\n");
  for (const id of [...covered].sort()) process.stdout.write(`  ${id}\n`);
}
