/**
 * Rule: document/iframe-title
 * Satisfies: wcag22:4.1.2, wcag21:4.1.2, wcag22:2.4.1, wcag21:2.4.1
 * Spec: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * > For all user interface components (including but not limited to:
 * > form elements, links and components generated by scripts), the
 * > name and role can be programmatically determined.
 *
 * Source: https://www.w3.org/TR/WCAG22/#name-role-value
 *
 * Flags `<iframe>` elements without a non-empty accessible name. The
 * HTML spec treats `title` as the primary mechanism for naming an
 * iframe, and ARIA Authoring Practices permit `aria-label` or
 * `aria-labelledby` as equivalent substitutes. Screen readers
 * announce a title-less iframe as the bare word "frame" with no
 * indication of its contents, which is a hard dead-end for users
 * navigating by rotor controls.
 *
 * Exception: iframes marked `aria-hidden="true"` are exempt — they
 * are explicitly removed from the accessibility tree so the lack of
 * a name is intentional.
 *
 * The rule also supports 2.4.1 (Bypass Blocks) as a secondary
 * criterion: an unlabeled iframe defeats any screen-reader strategy
 * to skip or traverse iframed content.
 */

import { defineRule } from "../../api/plugin.ts";
import {
  findHtmlElementsByTag,
  findJsxElementsByTag,
  getHtmlAttribute,
  getJsxAttribute,
  getJsxAttributeString,
  hasHtmlAttribute,
  hasJsxAttribute,
} from "../../engine/ast-helpers.ts";
import type { HtmlDocument, HtmlElement, JsxElement, TsxModule } from "../../types/ast.ts";

export const rule = defineRule({
  id: "document/iframe-title",
  satisfies: ["wcag22:4.1.2", "wcag21:4.1.2"],
  severity: "error",
  scope: "node",
  appliesTo: {
    fileExtensions: [".html", ".htm", ".tsx", ".jsx"],
  },
  docs: {
    description:
      "<iframe> elements must have a non-empty title, aria-label, or aria-labelledby so assistive technology can announce what the embedded frame contains.",
    rationale:
      "Screen readers announce an iframe by its accessible name. Without one, the user hears only 'frame' — no hint of whether it embeds a video, a form, an ad, or the main content. Rotor-based navigation becomes a dead end because every unnamed frame looks identical.",
    goodExample: `<iframe src="/video" title="Product demo video"></iframe>`,
    badExample: `<iframe src="/video"></iframe>`,
    normativeQuote:
      "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined.",
    references: [
      "https://www.w3.org/TR/WCAG22/#name-role-value",
      "https://www.w3.org/WAI/WCAG22/Techniques/html/H64",
    ],
  },
  check(ctx) {
    if (ctx.language === "html") {
      checkHtml(ctx.ast as HtmlDocument, (v) => ctx.emit(v));
    } else if (
      ctx.language === "tsx" ||
      ctx.language === "jsx" ||
      ctx.language === "ts" ||
      ctx.language === "js"
    ) {
      checkJsx(ctx.ast as TsxModule, (v) => ctx.emit(v));
    }
  },
});

type Emit = (v: {
  severity: "error" | "warning" | "info";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
}) => void;

function checkHtml(doc: HtmlDocument, emit: Emit): void {
  for (const iframe of findHtmlElementsByTag(doc, "iframe")) {
    if (getHtmlAttribute(iframe, "aria-hidden") === "true") continue;
    if (hasAccessibleNameHtml(iframe)) continue;
    emit(buildViolation(getHtmlAttribute(iframe, "src"), iframe.loc.start));
  }
}

function hasAccessibleNameHtml(element: HtmlElement): boolean {
  const title = getHtmlAttribute(element, "title");
  if (title !== null && title.trim().length > 0) return true;
  const ariaLabel = getHtmlAttribute(element, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  if (hasHtmlAttribute(element, "aria-labelledby")) {
    const labelledBy = getHtmlAttribute(element, "aria-labelledby");
    if (labelledBy !== null && labelledBy.trim().length > 0) return true;
  }
  return false;
}

function checkJsx(module: TsxModule, emit: Emit): void {
  for (const iframe of findJsxElementsByTag(module, "iframe")) {
    if (getJsxAttributeString(iframe, "aria-hidden") === "true") continue;
    if (hasAccessibleNameJsx(iframe)) continue;
    emit(buildViolation(getJsxAttributeString(iframe, "src"), iframe.loc.start));
  }
}

function hasAccessibleNameJsx(element: JsxElement): boolean {
  const title = getJsxAttributeString(element, "title");
  if (title !== null && title.trim().length > 0) return true;
  // Expression-valued title (e.g. title={t("frame")}) — trust the dev.
  const titleAttr = getJsxAttribute(element, "title");
  if (titleAttr?.value?.kind === "Expression") return true;
  const ariaLabel = getJsxAttributeString(element, "aria-label");
  if (ariaLabel !== null && ariaLabel.trim().length > 0) return true;
  const ariaLabelAttr = getJsxAttribute(element, "aria-label");
  if (ariaLabelAttr?.value?.kind === "Expression") return true;
  if (hasJsxAttribute(element, "aria-labelledby")) {
    const labelledBy = getJsxAttributeString(element, "aria-labelledby");
    if (labelledBy === null || labelledBy.trim().length > 0) return true;
  }
  return false;
}

function buildViolation(
  src: string | null,
  loc: { line: number; column: number },
): {
  severity: "error";
  location: { filePath: string; line: number; column: number };
  message: string;
  suggestion: string;
} {
  const subject = describeSource(src);
  return {
    severity: "error",
    location: { filePath: "", line: loc.line, column: loc.column },
    message: `<iframe>${subject.inMessage} has no accessible name — screen readers will announce it as 'frame' with no indication of what it contains.`,
    suggestion: `Add a descriptive title attribute${subject.inSuggestion} (e.g., title="${subject.example}"). An aria-label or aria-labelledby referencing a visible label is an equivalent fix. If the frame is purely decorative and holds nothing screen-reader users need, mark it with aria-hidden="true" instead.`,
  };
}

interface SourceDescription {
  readonly inMessage: string;
  readonly inSuggestion: string;
  readonly example: string;
}

function describeSource(src: string | null): SourceDescription {
  if (src === null || src.trim().length === 0) {
    return {
      inMessage: "",
      inSuggestion: "",
      example: "Embedded content description",
    };
  }
  const subject = guessSubjectFromUrl(src);
  return {
    inMessage: ` pointing at '${src}'`,
    inSuggestion: ` describing the embedded content`,
    example: subject,
  };
}

function guessSubjectFromUrl(src: string): string {
  // Strip query string and hash so "/video?autoplay=1" reads as "video".
  const pathOnly = src.split("?")[0]?.split("#")[0] ?? src;
  const trimmed = pathOnly.replace(/\/+$/, "");
  const slash = Math.max(trimmed.lastIndexOf("/"), trimmed.lastIndexOf("\\"));
  const tail = slash === -1 ? trimmed : trimmed.slice(slash + 1);
  const withoutExt = tail.replace(/\.[a-zA-Z0-9]+$/, "");
  const words = withoutExt.replace(/[-_]+/g, " ").trim();
  if (words.length === 0) return "Embedded content description";
  return words.charAt(0).toUpperCase() + words.slice(1);
}
